import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api, useRemote } from '../lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { PriorityQueue } from '../components/monitoring/PriorityQueue';
import { AuthorityMonitoring } from '../components/monitoring/AuthorityMonitoring';
import type { MonitoringCase } from '../lib/monitoring';
import { dateTime } from '../lib/monitoring';

type RequestRow={id:number;case_id:string;kind:string;status:string;created_at:string;reviewed_by:number|null;reviewed_at:string|null};
export function SupportRequests(){
 const {data,error,loading,refresh}=useRemote<{items:RequestRow[]}>('/api/support-requests');const[notice,setNotice]=useState('');const[busy,setBusy]=useState<number|null>(null);const staff=localStorage.getItem('role')!=='victim';
 async function update(id:number,status:string){setBusy(id);try{await api(`/api/support-requests/${id}`,{method:'PATCH',body:JSON.stringify({status})});await refresh();}catch(e){setNotice((e as Error).message);}finally{setBusy(null);}}
 return <Card><CardHeader><CardTitle>Support requests</CardTitle><p className="text-xs text-muted-foreground">Requests for human follow-up. This service is not continuously monitored.</p></CardHeader><CardContent className="space-y-3">{(error||notice)&&<p role="alert">{error||notice}</p>}{loading?<p>Loading requests...</p>:!data?.items.length?<p className="text-sm text-muted-foreground">No support requests yet.</p>:data.items.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="text-sm font-semibold">{r.kind} · {staff?<Link to={`/cases/${r.case_id}`}>{r.case_id}</Link>:'Your case'}</p><p className="text-xs text-muted-foreground">{dateTime(r.created_at)}{r.reviewed_at?` · Reviewed ${dateTime(r.reviewed_at)}`:''}</p></div><Badge>{r.status}</Badge>{staff&&r.status!=='Resolved'&&<div className="flex gap-2"><Button disabled={busy===r.id||r.status==='Reviewed'} size="sm" variant="outline" onClick={()=>void update(r.id,'Reviewed')}>Acknowledge</Button><Button disabled={busy===r.id} size="sm" onClick={()=>void update(r.id,'Resolved')}>Resolve</Button></div>}</div>)}</CardContent></Card>;
}
type Indicator={id:number;case_id:string;severity:string;source:string;reason:string;current_score:number|null;trend:string|null;created_at:string};
export function Alerts(){const {data,error,loading,refresh}=useRemote<{items:Indicator[]}>('/api/monitoring/indicators');const[busy,setBusy]=useState<number|null>(null);async function review(id:number){setBusy(id);try{await api(`/api/monitoring/indicators/${id}/review`,{method:'POST'});await refresh();}finally{setBusy(null);}}return <div className="space-y-6"><h1 className="text-2xl font-bold">Attention & follow-up</h1><SupportRequests/><Card><CardHeader><CardTitle>Priority monitoring queue</CardTitle><p className="text-sm text-muted-foreground">Persisted questionnaire/trend and successful AI signals requiring human review.</p></CardHeader><CardContent className="space-y-3">{error&&<p role="alert">{error}</p>}{loading?<p>Loading indicators...</p>:!data?.items.length?<p className="text-sm text-muted-foreground">No unacknowledged monitoring indicators.</p>:data.items.map(i=><article key={i.id} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><div><Link className="font-semibold text-primary" to={`/cases/${i.case_id}?indicator=${i.id}`}>{i.case_id}</Link><div className="mt-1 flex gap-2"><Badge>{i.severity}</Badge><Badge variant="outline">{i.source==='questionnaire_trend'?'Questionnaire trend':i.source==='questionnaire'?'Questionnaire':'Text AI'}</Badge></div></div><Button size="sm" disabled={busy===i.id} onClick={()=>void review(i.id)}>{busy===i.id?'Saving...':'Review'}</Button></div><p className="mt-3 text-sm">{i.reason}</p><p className="mt-2 text-xs text-muted-foreground">{i.current_score!==null?`Evidence score: ${i.current_score}/100 · `:''}{i.trend?`Trend: ${i.trend} · `:''}{dateTime(i.created_at)}</p><Link className="mt-2 inline-block text-sm text-primary" to={`/cases/${i.case_id}?indicator=${i.id}`}>Open case evidence</Link></article>)}</CardContent></Card><p className="text-xs text-muted-foreground">Support Requests are a separate human-request workflow. Questionnaire indicators are deterministic and are not AI-generated.</p></div>;}

type Staff={id:number;name:string;assigned_cases:number};type Case={caseId:string;assignedCounsellor:string;interventionStatus:string};
export function Counsellors(){const staff=useRemote<{items:Staff[]}>('/api/counsellors');const cases=useRemote<Case[]>('/api/cases');const[caseId,setCaseId]=useState('');const[id,setId]=useState('');const[status,setStatus]=useState('Monitoring');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api(`/api/cases/${encodeURIComponent(caseId)}/assignment`,{method:'PATCH',body:JSON.stringify({...(id?{counsellor_id:Number(id)}:{}),status})});setNotice('Assignment and status saved.');await Promise.all([staff.refresh(),cases.refresh()]);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-6"><h1 className="text-2xl font-bold">Counsellors & case assignment</h1>{(staff.error||cases.error)&&<p role="alert">{staff.error||cases.error}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{staff.data?.items.map(s=><Card key={s.id}><CardContent className="pt-5"><p className="font-semibold">{s.name}</p><p className="text-sm text-muted-foreground">{s.assigned_cases} assigned cases · availability is not tracked</p></CardContent></Card>)}</div>{staff.loading&&<p>Loading counsellors...</p>}{staff.data?.items.length===0&&<p>No counsellors registered. An operator must provision staff accounts.</p>}<Card><CardHeader><CardTitle>Assign or update a case</CardTitle></CardHeader><CardContent><form onSubmit={save} className="space-y-4"><label className="block text-sm">Case<select aria-label="Case" required className="mt-1 w-full rounded-lg border bg-card p-3" value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Choose a case</option>{cases.data?.map(c=><option key={c.caseId} value={c.caseId}>{c.caseId} · {c.assignedCounsellor} · {c.interventionStatus}</option>)}</select></label><label className="block text-sm">Counsellor<select aria-label="Counsellor" className="mt-1 w-full rounded-lg border bg-card p-3" value={id} onChange={e=>setId(e.target.value)}><option value="">Keep current assignment</option>{staff.data?.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="block text-sm">Case status<select aria-label="Case status" className="mt-1 w-full rounded-lg border bg-card p-3" value={status} onChange={e=>setStatus(e.target.value)}>{['Awaiting assignment','Monitoring','Follow-up pending','Rehabilitation','Closed'].map(s=><option key={s}>{s}</option>)}</select></label><Button disabled={busy||!caseId}>Save changes</Button><p role="status" className="text-sm">{notice}</p></form></CardContent></Card></div>;
}
export function Analytics(){const role=localStorage.getItem('role');const{data,error,loading,refresh}=useRemote<{items:MonitoringCase[]}>('/api/monitoring/cases');return <div className="space-y-6"><h1 className="text-2xl font-bold">Monitoring analytics</h1>{role==='authority'&&<AuthorityMonitoring/>}{error&&<p role="alert">{error}</p>}{loading?<p>Loading case indicators...</p>:<PriorityQueue items={data?.items??[]} onRefresh={()=>void refresh()}/>}</div>;}
export function Reports(){const{data,error,loading,refresh}=useRemote<{items:MonitoringCase[]}>('/api/monitoring/cases');function download(){const rows=data?.items??[];const lines=[['Case','Priority','Latest score','Risk','Trend','Review required','Latest activity'],...rows.map(r=>[r.case_id,r.category,r.current_score??'',r.current_risk??'',r.trend.state,r.needs_review?'Yes':'No',r.current_state_at??r.latest_activity??''])];const csv=lines.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='sahas-case-monitoring.csv';a.click();URL.revokeObjectURL(url);}
return <div className="space-y-5"><h1 className="text-2xl font-bold">Case monitoring report</h1><p className="text-sm text-muted-foreground">Export the cases authorized for your account. No message text or AI reasoning is included. Store exports securely.</p>{error&&<p role="alert">{error}</p>}<div className="flex gap-3"><Button disabled={loading||!data} onClick={download}>Download CSV</Button><Button variant="outline" onClick={()=>void refresh()}>Refresh</Button></div><p>{data?`${data.items.length} authorized cases available.`:'Loading...'}</p></div>;}
export function Settings(){return <Card><CardHeader><CardTitle>Your account</CardTitle></CardHeader><CardContent className="space-y-3"><p>{localStorage.getItem('name')}</p><p className="text-sm text-muted-foreground">Role: {localStorage.getItem('role')}</p><p className="text-sm">Use the theme control above to change appearance. Contact your project operator for password or account changes.</p><Button onClick={()=>{['access_token','isLoggedIn','role','name','email'].forEach(k=>localStorage.removeItem(k));location.assign('/login');}}>Sign out</Button></CardContent></Card>;}
