import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api,useRemote } from '../lib/api';
import { Button } from '../components/ui/button';
import { Card,CardContent,CardHeader,CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { dateTime } from '../lib/monitoring';
type Appointment={id:number;case_id:string;counsellor:string;starts_at:string;duration_minutes:number;status:string};
export function SessionList(){const{data,error,loading,refresh}=useRemote<{items:Appointment[]}>('/api/sessions');const[notice,setNotice]=useState('');const[busy,setBusy]=useState<number|null>(null);const role=localStorage.getItem('role');async function update(id:number,status:string){setBusy(id);try{await api(`/api/sessions/${id}`,{method:'PATCH',body:JSON.stringify({status})});await refresh();}catch(e){setNotice((e as Error).message);}finally{setBusy(null);}}
return <Card><CardHeader><CardTitle>Appointments</CardTitle><p className="text-xs text-muted-foreground">Requested times need staff confirmation. Conversations take place in case chat; video calling is not connected.</p></CardHeader><CardContent className="space-y-3">{(error||notice)&&<p role="alert">{error||notice}</p>}{loading?<p>Loading appointments...</p>:!data?.items.length?<p className="text-sm text-muted-foreground">No appointments scheduled yet.</p>:data.items.map(s=><div key={s.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{s.case_id} · {s.counsellor}</p><p className="text-sm text-muted-foreground">{dateTime(s.starts_at)} · {s.duration_minutes} minutes</p></div><Badge>{s.status}</Badge></div>{!['Completed','Cancelled'].includes(s.status)&&<div className="flex flex-wrap gap-2">{role!=='victim'&&s.status==='Requested'&&<Button disabled={busy===s.id} size="sm" onClick={()=>void update(s.id,'Confirmed')}>Confirm</Button>}{role!=='victim'&&s.status==='Confirmed'&&Date.parse(s.starts_at)<=Date.now()&&<Button disabled={busy===s.id} size="sm" onClick={()=>void update(s.id,'Completed')}>Mark completed</Button>}<Button disabled={busy===s.id} variant="outline" size="sm" onClick={()=>void update(s.id,'Cancelled')}>Cancel appointment</Button><Link className="p-2 text-sm text-primary" to={role==='victim'?'/victim':`/cases/${s.case_id}`}>Open case{role==='authority'?'':' conversation'}</Link></div>}</div>)}</CardContent></Card>;}
export default function Sessions(){const role=localStorage.getItem('role');const cases=useRemote<any>(role==='victim'?'/api/victim/dashboard':'/api/cases');const[caseId,setCaseId]=useState('');const[starts,setStarts]=useState('');const[duration,setDuration]=useState(45);const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[revision,setRevision]=useState(0);const options:Array<{caseId:string}>=role==='victim'?(cases.data?[cases.data]:[]):cases.data??[];
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice('');try{await api('/api/sessions',{method:'POST',body:JSON.stringify({case_id:caseId||options[0]?.caseId,starts_at:new Date(starts).toISOString(),duration_minutes:duration})});setNotice('Appointment saved. Victim requests await staff confirmation.');setRevision(v=>v+1);setStarts('');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
return <div className="space-y-6"><h1 className="text-2xl font-bold">Sessions</h1><SessionList key={revision}/><Card><CardHeader><CardTitle>{role==='victim'?'Request an appointment':'Schedule an appointment'}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{cases.error&&<p role="alert">{cases.error}</p>}<label className="block text-sm">Case<select aria-label="Appointment case" required className="mt-1 w-full rounded-lg border bg-card p-3" value={caseId||options[0]?.caseId||''} onChange={e=>setCaseId(e.target.value)}>{!options.length&&<option value="">No authorized cases available</option>}{options.map(c=><option key={c.caseId}>{c.caseId}</option>)}</select></label><label className="block text-sm">Date and time (your local timezone)<input aria-label="Date and time" type="datetime-local" required className="mt-1 w-full rounded-lg border bg-card p-3" value={starts} onChange={e=>setStarts(e.target.value)}/></label><label className="block text-sm">Duration in minutes<input aria-label="Duration in minutes" type="number" min={15} max={120} required className="mt-1 w-full rounded-lg border bg-card p-3" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><Button disabled={busy||!options.length}>{busy?'Saving...':'Save appointment'}</Button><p role="status" className="text-sm">{notice}</p></form></CardContent></Card></div>;}
